# Generated by Django 3.2.1 on 2023-10-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
